# Generated by Django 5.2.1 on 2025-09-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_app_logo_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded photo for Railway compatibility', null=True),
        ),
    ]
